/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package silviialya;

/**
 *
 * @author SILVI ALYA ZAHRA
 */
public class kalkulator extends javax.swing.JFrame {
    String angka;
     double jumlah,bil1,bil2;
     int pilih;

    /**
     * Creates new form kalkulator
     */
    public kalkulator(){
        initComponents() ;
         angka="";
    }
  
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: DO NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")

}
